#!/usr/bin/env bash

# This script will create a shortcut on applications menu for windows programs installed with wine.
# by Thiago silva

# Test if there is a argument.
if [[ $(file --mime-type -b "$1") = application/* ]]

then

# Get the full path, the name and directory name of submited application file. 
	myFile=$(realpath "$1")
	myBaseName=$(basename "$myFile")
	myPath=$(dirname "$myFile")

# Extract icon and convert it to several png files of diferent quality, selecting the best one.
	echo "Extracting icon..."
	wrestool -x -t 14 "$myFile" > "/tmp/$myBaseName.ico"
	echo Converting icon to png files...
	convert -alpha on "/tmp/$myBaseName.ico" "/tmp/$myBaseName.png"
	echo Copying "$(ls -S -1 "/tmp/$myBasename"*".png" | head -n 1)" to "$myFile.icon.png" ...
	cp "$(ls -S -1 "/tmp/$myBaseName"*".png"  | head -n 1)" "$myFile.icon.png"

# Display graphical dialog boxes to receive category and name inputs from the user.
	appCategory=$(zenity --title "wine-create-shortcut" --height=450 --list --radiolist --column " " \
--column "Categories" 0 AudioVideo 0 Audio 0 Video 0 Development 0 Education TRUE Game 0 Graphics 0 \
Network 0 Office 0 Settings 0 System 0 Utility  --text "Select a Category:")
	appName=$(zenity --title "wine-create-shortcut" --text "Enter a name for your shortcut" --entry)

# Generate desktop entry specifications to be added to the application launcher.
	echo Creating shortcut contents...
	deskEntry="[Desktop Entry]"\\n"Exec=wine start /Unix \""$myFile"\""\\n"Name=$appName"\\n"Path=$myPath"\
\\n"Type=Application"\\n"Categories=Application;$category;"\\n"Icon="$myFile.icon.png""

# Create a .desktop file and add desktop entries in it, then link the launcher file to a shortcut on applications menu
	echo Creating .desktop file...
	echo -e $deskEntry >"$myFile".desktop
	echo Creating link on applications menu...
	ln -s "$myFile.desktop" "$HOME/.local/share/applications/$myBaseName.desktop"

# show this message when script has finished.
	echo "Done."

else 

# If no application was submited, show this message.
	echo Please, submit a windows application file. 
	echo Usage: ./wine-create-shortcut path/to/app.exe 
	echo

fi
